server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona qualquer rota para o index.html (necessário para React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}